<?php

namespace Proxies\__CG__\Dwm\CatalogueBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class command extends \Dwm\CatalogueBundle\Entity\command implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getClient()
    {
        $this->__load();
        return parent::getClient();
    }

    public function setClient($client)
    {
        $this->__load();
        return parent::setClient($client);
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setDatecmd($datecmd)
    {
        $this->__load();
        return parent::setDatecmd($datecmd);
    }

    public function getDatecmd()
    {
        $this->__load();
        return parent::getDatecmd();
    }

    public function setDateliv($dateliv)
    {
        $this->__load();
        return parent::setDateliv($dateliv);
    }

    public function getDateliv()
    {
        $this->__load();
        return parent::getDateliv();
    }

    public function setAdresse($adresse)
    {
        $this->__load();
        return parent::setAdresse($adresse);
    }

    public function getAdresse()
    {
        $this->__load();
        return parent::getAdresse();
    }

    public function setTotalttc($totalttc)
    {
        $this->__load();
        return parent::setTotalttc($totalttc);
    }

    public function getTotalttc()
    {
        $this->__load();
        return parent::getTotalttc();
    }

    public function setEtatcom($etatcom)
    {
        $this->__load();
        return parent::setEtatcom($etatcom);
    }

    public function getEtatcom()
    {
        $this->__load();
        return parent::getEtatcom();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'datecmd', 'dateliv', 'adresse', 'totalttc', 'etatcom', 'client');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}